# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nitric/proto/batch/v1/batch.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class CreateJobRequest(betterproto.Message):
    """ClientMessages are sent from the service to the nitric server"""

    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class CreateJobResponse(betterproto.Message):
    pass


class BatchStub(betterproto.ServiceStub):
    async def create_job(
        self,
        create_job_request: "CreateJobRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CreateJobResponse":
        return await self._unary_unary(
            "/nitric.proto.batch.v1.Batch/CreateJob",
            create_job_request,
            CreateJobResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class BatchBase(ServiceBase):
    async def create_job(
        self, create_job_request: "CreateJobRequest"
    ) -> "CreateJobResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_create_job(
        self, stream: "grpclib.server.Stream[CreateJobRequest, CreateJobResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.create_job(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/nitric.proto.batch.v1.Batch/CreateJob": grpclib.const.Handler(
                self.__rpc_create_job,
                grpclib.const.Cardinality.UNARY_UNARY,
                CreateJobRequest,
                CreateJobResponse,
            ),
        }
