# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nitric/proto/http/v1/http.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    AsyncIterable,
    AsyncIterator,
    Dict,
    Iterable,
    Optional,
    Union,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class ClientMessage(betterproto.Message):
    request: "HttpProxyRequest" = betterproto.message_field(1)
    """Details of the HTTP server to proxy"""


@dataclass(eq=False, repr=False)
class ServerMessage(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class HttpProxyRequest(betterproto.Message):
    host: str = betterproto.string_field(1)
    """The address the server can be accessed on"""


class HttpStub(betterproto.ServiceStub):
    async def proxy(
        self,
        client_message_iterator: Union[AsyncIterable["ClientMessage"], Iterable["ClientMessage"]],
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator["ServerMessage"]:
        async for response in self._stream_stream(
            "/nitric.proto.http.v1.Http/Proxy",
            client_message_iterator,
            ClientMessage,
            ServerMessage,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


class HttpBase(ServiceBase):
    async def proxy(self, client_message_iterator: AsyncIterator["ClientMessage"]) -> AsyncIterator["ServerMessage"]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield ServerMessage()

    async def __rpc_proxy(self, stream: "grpclib.server.Stream[ClientMessage, ServerMessage]") -> None:
        request = stream.__aiter__()
        await self._call_rpc_handler_server_stream(
            self.proxy,
            stream,
            request,
        )

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/nitric.proto.http.v1.Http/Proxy": grpclib.const.Handler(
                self.__rpc_proxy,
                grpclib.const.Cardinality.STREAM_STREAM,
                ClientMessage,
                ServerMessage,
            ),
        }
