# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nitric/proto/sql/v1/sql.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class SqlConnectionStringRequest(betterproto.Message):
    database_name: str = betterproto.string_field(1)
    """The name of the database to retrieve the connection string for"""


@dataclass(eq=False, repr=False)
class SqlConnectionStringResponse(betterproto.Message):
    connection_string: str = betterproto.string_field(1)
    """The connection string for the database"""


class SqlStub(betterproto.ServiceStub):
    async def connection_string(
        self,
        sql_connection_string_request: "SqlConnectionStringRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SqlConnectionStringResponse":
        return await self._unary_unary(
            "/nitric.proto.sql.v1.Sql/ConnectionString",
            sql_connection_string_request,
            SqlConnectionStringResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SqlBase(ServiceBase):
    async def connection_string(
        self, sql_connection_string_request: "SqlConnectionStringRequest"
    ) -> "SqlConnectionStringResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_connection_string(
        self,
        stream: "grpclib.server.Stream[SqlConnectionStringRequest, SqlConnectionStringResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.connection_string(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/nitric.proto.sql.v1.Sql/ConnectionString": grpclib.const.Handler(
                self.__rpc_connection_string,
                grpclib.const.Cardinality.UNARY_UNARY,
                SqlConnectionStringRequest,
                SqlConnectionStringResponse,
            ),
        }
