import glob
import fileinput
import os
import re

AUTO_GEN_PATH = "../nitric/proto/**/*_pb2*.py"
REPLACE = re.compile(r"^from (?=.*.v1 import)")
WITH = "from nitric.proto."


def main():
    """Fix the import statements generated by protoc for python."""
    tools_dir = os.path.dirname(__file__)
    gen_dir = os.path.join(tools_dir, AUTO_GEN_PATH)
    grcp_paths = glob.glob(gen_dir, recursive=True)

    for path in grcp_paths:
        print("fixing imports in {path}".format(path=path))
        with fileinput.FileInput(path, inplace=True) as file:
            for line in file:
                if not line.startswith(WITH):
                    line = REPLACE.sub(WITH, line)
                print(line, end="")


if __name__ == "__main__":
    main()
