#
# Copyright (c) 2021 Nitric Technologies Pty Ltd.
#
# This file is part of Nitric Python 3 SDK.
# See https://github.com/nitrictech/python-sdk for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import glob
import fileinput
import os
import re

AUTO_GEN_PATH = "../nitric/proto/**/*_pb2*.py"
REPLACE = re.compile(r"^from (?=.*.v1 import)")
WITH = "from nitric.proto."


def main():
    """Fix the import statements generated by protoc for python."""
    tools_dir = os.path.dirname(__file__)
    gen_dir = os.path.join(tools_dir, AUTO_GEN_PATH)
    grcp_paths = glob.glob(gen_dir, recursive=True)

    for path in grcp_paths:
        print("fixing imports in {path}".format(path=path))
        with fileinput.FileInput(path, inplace=True) as file:
            for line in file:
                if not line.startswith(WITH):
                    line = REPLACE.sub(WITH, line)
                print(line, end="")


if __name__ == "__main__":
    main()
